### ISSUE TITLE
Fail to decrypt message: Given final block not properly padded. Such issues can arise if a bad key is used during decryption

### ISSUE THREAD

**Issue by ichwansh03** [forcedotcom/dataloader#1287]
**Describe the bug**
Before I try `dataloader-54.0.0`, I first used the `dataloader-40.0.0` and there are no problems at all when the key encryption process, the data is successfully uploaded to SFDC. However when I changed to `dataloader-54.0.0`, I had a failure when encrypting the key. I encrypted the sfdc password and security token, whereas in the previous version I used in `dataloader-40.0.0`, I didn't need to encrypt the security token, only the sfdc and proxy password. Why does the `dataloader-54.0.0` have problems with encryption with error like this `security.EncryptionAesUtil decryptMsg (EncryptionAesUtil.java:217) - Fail to decrypt message: Given final block not properly padded. Such issues can arise if a bad key is used during decryption`? Is there a wrong process when I am logging or is there a lack of configuration in my settings? 

**To Reproduce**
1. Create generate key file with command `encrypt.bat -g SECRETKEY` inside path `D:\Application\Consoles\dataloader\v54.0.0\bin`
2. Copy generated key to file `sample.key`
3. Run command `encrypt.bat -e <SFDCPassword+SecurityToken> <key path file>`
4. Copy encrypted key and set to sfdc.password in `process-conf.xml`
Here's is my `config.properties`:
```
#Loader Config
dataAccess.readUTF8=true
dataAccess.writeUTF8=true
process.enableExtractStatusOutput=true
process.enableLastRunOutput=true
sfdc.bulkApiCheckStatusInterval=5000
sfdc.bulkApiSerialMode=5000
sfdc.debugMessages=false
sfdc.enableRetries=true
sfdc.extractionRequestSize=500
sfdc.insertNulls=true
sfdc.loadBatchSize=200
sfdc.maxRetries=3
sfdc.minRetrySleepSecs=2
sfdc.noCompression=false
sfdc.timeoutSecs=60
sfdc.useBulkApi=false
sfdc.proxyHost=<proxyhost>
sfdc.proxyPort=8080
dataAccess.type=csvRead
```

`process-conf.xml`:
```
<beans>
	<bean id="RDSBox" class="com.salesforce.dataloader.process.ProcessRunner" scope="prototype">
		<description>Upsert RDSBox</description>
        <property name="name" value="RDSBox"/>
        <property name="configOverrideMap">
            <map>
		<entry key="sfdc.endpoint" value="https://test.salesforce.com"/>
                <entry key="sfdc.username" value="username"/>
                <entry key="sfdc.password" value="very long encrypt"/>
                <entry key="process.encryptionKeyFile" value="D:\Application\Consoles\configSandbox\sample.key"/>
		//another entry
            </map>
        </property>
    </bean>
</beans>
```

Call DataLoaderRunner class in batch file:
```
CALL "C:\Program Files\Java\jdk-11.0.16\bin"\java -cp "%l_dir_dataloader%"\dataloader-54.0.0-uber.jar -Dsalesforce.config.dir="%l_dir_config%" com.salesforce.dataloader.process.DataLoaderRunner process.name=RDSBox run.mode=batch>> %l_log_file%
```

Here's a detail log result:
```
2024-09-27 09:03:53,409 INFO  [RDSBox] controller.Controller initConfig (Controller.java:405) - The controller config has been initialized
2024-09-27 09:03:53,409 ERROR [RDSBox] security.EncryptionAesUtil decryptMsg (EncryptionAesUtil.java:217) - Fail to decrypt message: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
2024-09-27 09:03:53,409 ERROR [RDSBox] config.Config decryptProperty (Config.java:841) - Error loading parameter: sfdc.password of type: java.lang.String
java.security.GeneralSecurityException: Error to decrypt message: 
	at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:218) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:835) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:794) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.postLoad(Config.java:774) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:815) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.initConfig(Controller.java:407) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.<init>(Controller.java:129) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.getInstance(Controller.java:292) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:124) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:262) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:246) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:104) [dataloader-54.0.0-uber.jar:?]
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975) ~[?:?]
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056) ~[?:?]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853) ~[?:?]
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446) ~[?:?]
	at javax.crypto.Cipher.doFinal(Cipher.java:2202) ~[?:?]
	at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:241) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:215) ~[dataloader-54.0.0-uber.jar:?]
	... 11 more
2024-09-27 09:03:53,426 ERROR [RDSBox] controller.Controller <init> (Controller.java:131) - Exception happened in initConfig:
com.salesforce.dataloader.exception.ControllerInitializationException: Error loading config file: D:\Application\Consoles\configSandbox\config.properties.  Please make sure that it exists and is readable
	at com.salesforce.dataloader.controller.Controller.initConfig(Controller.java:411) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.<init>(Controller.java:129) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.getInstance(Controller.java:292) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:124) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:262) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:246) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:104) [dataloader-54.0.0-uber.jar:?]
Caused by: com.salesforce.dataloader.exception.ParameterLoadException: Error loading parameter: sfdc.password of type: java.lang.String
	at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:842) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:794) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.postLoad(Config.java:774) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:815) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.initConfig(Controller.java:407) ~[dataloader-54.0.0-uber.jar:?]
	... 6 more
Caused by: java.security.GeneralSecurityException: Error to decrypt message: 
	at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:218) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:835) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:794) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.postLoad(Config.java:774) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:815) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.initConfig(Controller.java:407) ~[dataloader-54.0.0-uber.jar:?]
	... 6 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975) ~[?:?]
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056) ~[?:?]
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853) ~[?:?]
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446) ~[?:?]
	at javax.crypto.Cipher.doFinal(Cipher.java:2202) ~[?:?]
	at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:241) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:215) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:835) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:794) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.postLoad(Config.java:774) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:815) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.initConfig(Controller.java:407) ~[dataloader-54.0.0-uber.jar:?]
	... 6 more
```

**Device & tools:**
 - OS: Windows 11
 - Java: JDK 11.0.6
 - Dataloader: 54.0.0

**Comment by ashitsalesforce** [comment]
Hi @ichwansh03 , what is the location of the key file? Is it a file in `D:\Application\Consoles\dataloader\v54.0.0\bin` folder or `D:\Application\Consoles\configSandbox\sample.key`?

You can try to troubleshoot by running the command `encrypt -d <encrypted key+token> <file name of the keyfile using the full path>` and see the output. Make sure that the name of the keyfile is the same as the one used in `encrypt -e ` command.

**Comment by ichwansh03** [comment]
Hi @ashitsalesforce, thanks for your respond. I put key file in `D:\Application\Consoles\configSandbox\sample.key`, so it's different directory from dataloader.
And then, I try to validate encrypted key for sfdc password and token. Here'a a result:
![Capture](https://github.com/user-attachments/assets/feb17bb0-f3b8-4a11-b7d2-87ba73b880d0)

**Comment by ashitsalesforce** [comment]
Hi @ichwansh03 , I have not seen -v option for encrypt utility before in code or in documentation. Did you modify the code to support it? Also, did you try again after verifying that decryption works?

**Comment by ichwansh03** [comment]
Hi @ashitsalesforce, I don't know why my encrypt.bat has no option to use -d or -k. Only -g, -v and -e. Do I have to use the latest version of dataloader or you have any reference?
![Capture](https://github.com/user-attachments/assets/3570de56-8b01-45d1-8cee-f8c6798eb806)

**Comment by ashitsalesforce** [comment]
The class, EncryptionUtil.java has the change history [here](https://github.com/forcedotcom/dataloader/commits/dca16817c439edd64ce58482d92f8977c4e46f86/src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java). The last change was made by me 4 years ago on October 15, 2020, which is before [v54.0.0 release](https://github.com/forcedotcom/dataloader/releases/tag/v54.0.0) (Jan 07, 2022). Looking at the [code of EncryptionUtil.java](https://github.com/forcedotcom/dataloader/blob/7ff5922a616cf2c640d2584fa07655a9a3f8655e/src/main/java/com/salesforce/dataloader/security/EncryptionUtil.java) , the options are listed on lines 74 through 78. They are: -e, -k, and -d.

A code change checked in on Feb 12, 2018 changed options from -g, -v, -e to -e, -k, -d. So, I suspect that you are encrypting your password+token with older version of encrypt.bat (older than v54.0.0) that uses older Java utilities for encrypting the password+token. When you run data loader v54.0.0, it tries to decrypt the password with newer version of Java utilities, which results in the issue.

To make sure that you are using the right encrypt.bat, go to `D:\Application\Consoles\dataloader\v54.0.0\bin` folder and run `.\encrypt.bat` command without any options. If it shows -e, -d, -k in its usage string then you know you are executing the right command. Next, try `.\encrypt.bat -e password+token` and specify the encoded password it in process-conf.xml.

**Comment by ashitsalesforce** [comment]
Hi @ichwansh03 , good to hear that your issue is resolved. We recommend switching to the latest version of Data Loader (v62.0.1) and continue to do so with each release as new releases use Java runtime that's currently supported by major vendors including Oracle, IBM, and others. For example, JRE 11 required by v54.0.0 is no longer supported by Java vendors. The latest Data Loader release requires JRE 17 or later, which is the earliest Java version supported by Java vendors. 

Moreover, the latest Data Loader release contains the latest version of libraries such as log4j that contain fixes for major vulnerabilities. 

Lastly, we fix critical issues in the latest version only. Which means if you are using previous release and encounter an issue, it may be more challenging for you to migrate to the latest version.
