### ISSUE TITLE
Unable to start on macOS 10.15.6

### ISSUE THREAD

**Issue by adtennant** [forcedotcom/dataloader#215]
After installing Zulu and installing Dataloader v50.0.0 I get the following error on startup. The same issue occurs with versions back to v45.0.0:
```
2020-09-01 16:59:45,124 INFO  [main] controller.Controller initLog (Controller.java:468) - Reading log-conf.xml in /Users/alex/dataloader/v50.0.0/configs/log-conf.xml
2020-09-01 16:59:45,149 INFO  [main] controller.Controller initLog (Controller.java:477) - The log has been initialized
2020-09-01 16:59:45,158 INFO  [main] controller.Controller createDir (Controller.java:306) - Config directory already exists: /Users/alex/dataloader/v50.0.0/configs
2020-09-01 16:59:45,159 INFO  [main] controller.Controller initConfig (Controller.java:396) - Looking for file in config path: /Users/alex/dataloader/v50.0.0/configs/config.properties
2020-09-01 16:59:45,159 INFO  [main] controller.Controller initConfig (Controller.java:429) - User config is found in /Users/alex/dataloader/v50.0.0/configs/config.properties
2020-09-01 16:59:45,232 INFO  [main] controller.Controller initConfig (Controller.java:439) - The controller config has been initialized
2020-09-01 16:59:45,731 INFO  [main] config.LastRun load (LastRun.java:96) - Last run info will be saved in file: /Users/alex/dataloader/v50.0.0/configs/ui_lastRun.properties
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.custom.CLabel.getTotalSize(Unknown Source)
	at org.eclipse.swt.custom.CLabel.onPaint(Unknown Source)
	at org.eclipse.swt.custom.CLabel$1.paintControl(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Control.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Widget.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.applicationProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at com.salesforce.dataloader.ui.LoaderWindow.run(LoaderWindow.java:149)
	at com.salesforce.dataloader.controller.Controller.createAndShowGUI(Controller.java:266)
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:50)
```

**Comment by vasfdc** [comment]
Still facing this issue. Have installed v44.0 with jdk8

**Comment by bahmanashtari** [comment]
Facing this same issue has taken so much of my time. I've tried different combinations of JDK and data loader versions, as well as Zulu version. Nothing works.

**Comment by bahmanashtari** [comment]
I found a way to make this work. Here's a link to my description of how I did it. I hope it helps you.
https://salesforce.stackexchange.com/questions/318084/data-loader-on-macos-java-lang-nullpointerexception-with-zulu-openjdk-11/327206#327206

**Comment by ptorric** [comment]
no way on v50 and macOs 11.0.1 (Big Sur).
any ideas?

**Comment by ashitsalesforce** [comment]
Closing as v51 (latest release) supports Big Sur.
