### ISSUE TITLE
Dataloader v50.0.0 throwing null pointer on startup

### ISSUE THREAD

**Issue by markstonehouse** [forcedotcom/dataloader#231]
The below error message is given as an output to the terminal window on start up of the Dataloader application.
**Operating System**: Mac OSX Big Sur
Zulu-v1.jdk is installed
![image](https://user-images.githubusercontent.com/22397019/100221378-84448f80-2f10-11eb-9bba-9cbe5885cb95.png)

I have also followed the steps here in this pull request but the error persists: https://github.com/forcedotcom/dataloader/issues/179#issuecomment-690342373

`/Library/Java/JavaVirtualMachines/zulu-14.jdk/Contents/Home
2020-11-25 11:12:10,556 INFO  [main] controller.Controller initLog (Controller.java:468) - Reading log-conf.xml in /Users/markstonehouse/dataloader/v50.0.0/configs/log-conf.xml
2020-11-25 11:12:10,576 INFO  [main] controller.Controller initLog (Controller.java:477) - The log has been initialized
2020-11-25 11:12:10,584 INFO  [main] controller.Controller createDir (Controller.java:306) - Config directory already exists: /Users/markstonehouse/dataloader/v50.0.0/configs
2020-11-25 11:12:10,584 INFO  [main] controller.Controller initConfig (Controller.java:396) - Looking for file in config path: /Users/markstonehouse/dataloader/v50.0.0/configs/config.properties
2020-11-25 11:12:10,584 INFO  [main] controller.Controller initConfig (Controller.java:429) - User config is found in /Users/markstonehouse/dataloader/v50.0.0/configs/config.properties
2020-11-25 11:12:10,632 INFO  [main] controller.Controller initConfig (Controller.java:439) - The controller config has been initialized
2020-11-25 11:12:11,060 INFO  [main] config.LastRun load (LastRun.java:96) - Last run info will be saved in file: /Users/markstonehouse/dataloader/v50.0.0/configs/ui_lastRun.properties
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.custom.CLabel.getTotalSize(Unknown Source)
	at org.eclipse.swt.custom.CLabel.onPaint(Unknown Source)
	at org.eclipse.swt.custom.CLabel$1.paintControl(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Control.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Widget.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.applicationProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at com.salesforce.dataloader.ui.LoaderWindow.run(LoaderWindow.java:149)
	at com.salesforce.dataloader.controller.Controller.createAndShowGUI(Controller.java:266)
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:50)
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.custom.CLabel.getTotalSize(Unknown Source)
	at org.eclipse.swt.custom.CLabel.onPaint(Unknown Source)
	at org.eclipse.swt.custom.CLabel$1.paintControl(Unknown Source)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Control.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawWidget(Unknown Source)
	at org.eclipse.swt.widgets.Widget.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.drawRect(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.applicationProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at com.salesforce.dataloader.ui.LoaderWindow.run(LoaderWindow.java:149)
	at com.salesforce.dataloader.controller.Controller.createAndShowGUI(Controller.java:266)
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:50)
`

**Comment by escaleraalcielo** [comment]
There's another issue reporting this, it seems they're gonna release a corrected version next month.

Meanwhile they've unofficialy released an corrected version that you can check here
Have a nice day!

#https://github.com/forcedotcom/dataloader/issues/217#issuecomment-733944644

**Comment by markstonehouse** [comment]
This works @escaleraalcielo, thanks for your help!
