### ISSUE TITLE
Data Loader - Not able to change Bulk API/batch settings and upload files with specific delimiter 

### ISSUE THREAD

**Issue by yannibenoit** [forcedotcom/dataloader#232]
Thanks very much for the fix
The application start now but I have issues using the settings 
I'm not able to save my settings when I select the Bulk API or change the batch rows value
![image](https://user-images.githubusercontent.com/19322787/100340263-35aff780-2fdb-11eb-9fb9-9481a11cc869.png)
or upload files with specific delimiters (`| `for example). It was working fine on the last version.
![image](https://user-images.githubusercontent.com/19322787/100340418-73ad1b80-2fdb-11eb-8786-344e90ef89a2.png)

```
2020-11-26 11:34:12,069 INFO  [main] action.OperationInfo instantiateWizard (OperationInfo.java:138) - Instantiating wizard: insert
2020-11-26 11:34:31,748 INFO  [main] dao.DataAccessObjectFactory getDaoInstance (DataAccessObjectFactory.java:51) - Instantiating data access object: /Users/yanni/Documents/to_salesforce/files_downloaded_prepared.csv of type: csvRead
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.salesforce.dataloader.dao.csv.CSVFileReader.readRow(CSVFileReader.java:223)
	at com.salesforce.dataloader.util.DAORowUtil.calculateTotalRows(DAORowUtil.java:67)
	at com.salesforce.dataloader.dao.csv.CSVFileReader.getTotalRows(CSVFileReader.java:250)
	at com.salesforce.dataloader.ui.DataSelectionDialog$1.run(DataSelectionDialog.java:163)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at com.salesforce.dataloader.ui.DataSelectionDialog.open(DataSelectionDialog.java:115)
	at com.salesforce.dataloader.ui.DataSelectionPage.getNextPage(DataSelectionPage.java:261)
	at com.salesforce.dataloader.ui.DataSelectionPage.getNextPage(DataSelectionPage.java:58)
	at com.salesforce.dataloader.ui.LoaderWizardDialog.nextPressed(LoaderWizardDialog.java:726)
	at com.salesforce.dataloader.ui.LoaderWizardDialog.buttonPressed(LoaderWizardDialog.java:308)
	at com.salesforce.dataloader.ui.LoaderWizardDialog$5.widgetSelected(LoaderWizardDialog.java:1252)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4385)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3789)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.salesforce.dataloader.ui.uiActions.OperationUIAction.run(OperationUIAction.java:54)
	at com.salesforce.dataloader.ui.LoaderWindow$2.widgetSelected(LoaderWindow.java:238)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4385)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3789)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.salesforce.dataloader.ui.LoaderWindow.run(LoaderWindow.java:149)
	at com.salesforce.dataloader.controller.Controller.createAndShowGUI(Controller.java:266)
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:50)


```

**Comment by ashitsalesforce** [comment]
Hi yannibenoit, 

I am able to successfully do both operations on MacOS Catalina and MacOS Big Sur. The operations I performed are: 
1. Able to change Bulk API/batch settings. For example, select the checkbox "Use Bulk API" or change the value of "Batch Size". 
2. Upload CSV file with the vertical bar character ('|') as the delimiter for Insert operation.

Please reach out to Salesforce Support to resolve your issues. Also, provide the full exception stack trace for both issues to help resolve them. The exception stack trace you have captured for the issue #2 is complete whereas the stack trace for the issue #1 isn't. Having a complete stack trace will help troubleshoot the root-cause.

**Comment by yannibenoit** [comment]
> Hi yannibenoit,
> 
> I am able to successfully do both operations on MacOS Catalina and MacOS Big Sur. The operations I performed are:
> 
> 1. Able to change Bulk API/batch settings. For example, select the checkbox "Use Bulk API" or change the value of "Batch Size".
> 2. Upload CSV file with the vertical bar character ('|') as the delimiter for Insert operation.
> 
> Please reach out to Salesforce Support to resolve your issues. Also, provide the full exception stack trace for both issues to help resolve them. The exception stack trace you have captured for the issue #2 is complete whereas the stack trace for the issue #1 isn't. Having a complete stack trace will help troubleshoot the root-cause.

Ok fine I will contact the support, but I'm not able to upload any csv files using ',' separator or '|' using[ this version
](https://github.com/forcedotcom/dataloader/files/5599246/dataloader_mac.zip)
![image](https://user-images.githubusercontent.com/19322787/100381089-7f6b0300-3018-11eb-87b4-a920c4e58715.png)

```
 Instantiating wizard: insert
2020-11-26 18:50:19.747 java[95433:2192629] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fa7676fd4a0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2020-11-26 18:50:31,825 INFO  [main] client.PartnerClient login (PartnerClient.java:500) - Beginning Partner Salesforce login ....
2020-11-26 18:50:31,880 INFO  [main] client.PartnerClient setConfiguredSessionId (PartnerClient.java:530) - Using manually configured session id to bypass login
2020-11-26 18:51:01,342 INFO  [main] dao.DataAccessObjectFactory getDaoInstance (DataAccessObjectFactory.java:51) - Instantiating data access object: /Users/yanni/Desktop/files_downloaded_prepared.csv of type: csvRead
2020-11-26 18:51:01,350 WARN  [main] util.DAORowUtil validateColumns (DAORowUtil.java:121) - An empty column is found
2020-11-26 18:51:01.432 java[95433:2192629] Warning: Expected min height of view: (<NSButton: 0x7fa767a82df0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2020-11-26 18:51:01.435 java[95433:2192629] Warning: Expected min height of view: (<NSButton: 0x7fa767a7cb00>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
```

**Comment by ashitsalesforce** [comment]
Closing the issue due to inactivity.
