### ISSUE TITLE
process-conf.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 29; Attribute "singleton" must be declared for element type "bean".

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/dataloader#240]
Hello - I just saw new data loader version 51 so thought let me try it out and getting below error

I've uploaded process-config file

PS C:\dataloader\v51.0.0\INT> ./accountUpsert.ps1
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
15:50:16.673 [main] ERROR com.salesforce.dataloader.process.ProcessConfig - Error loading process: LNaccountUpsert configuration from config file: C:\dataloader\v51.0.0\INT\process-conf.xml
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 6 in XML document from file [C:\dataloader\v51.0.0\INT\process-conf.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 29; Attribute "singleton" must be declared for element type "bean".
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:402) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:338) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:638) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85) ~[dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessConfig.getBeanFactory(ProcessConfig.java:112) ~[dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:94) [dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:302) [dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:288) [dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:261) [dataloader-51.0.0-uber.jar:?]
Caused by: org.xml.sax.SAXParseException: Attribute "singleton" must be declared for element type "bean".
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204) ~[?:?]
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1237) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1846) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:728) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) ~[?:?]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) ~[?:?]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[?:?]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:?]
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246) ~[?:?]
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
        at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:432) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390) ~[dataloader-51.0.0-uber.jar:?]
        ... 18 more
15:50:16.724 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Failed to create process
com.salesforce.dataloader.exception.ProcessInitializationException: Error loading process: LNaccountUpsert configuration from config file: C:\dataloader\v51.0.0\INT\process-conf.xml
        at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:98) ~[dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:302) ~[dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:288) [dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:261) [dataloader-51.0.0-uber.jar:?]
Caused by: org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 6 in XML document from file [C:\dataloader\v51.0.0\INT\process-conf.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 29; Attribute "singleton" must be declared for element type "bean".
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:402) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:338) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:638) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85) ~[dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessConfig.getBeanFactory(ProcessConfig.java:112) ~[dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:94) ~[dataloader-51.0.0-uber.jar:?]
        ... 3 more
Caused by: org.xml.sax.SAXParseException: Attribute "singleton" must be declared for element type "bean".
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204) ~[?:?]
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1237) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1846) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:728) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[?:?]
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) ~[?:?]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) ~[?:?]
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[?:?]
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:?]
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246) ~[?:?]
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
        at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:432) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:338) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:638) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142) ~[dataloader-51.0.0-uber.jar:?]
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85) ~[dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessConfig.getBeanFactory(ProcessConfig.java:112) ~[dataloader-51.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:94) ~[dataloader-51.0.0-uber.jar:?]
        ... 3 more
[process-config.txt](https://github.com/forcedotcom/dataloader/files/5789325/process-config.txt)

**Comment by ashitsalesforce** [comment]
Hi gvpatel,

Make sure that your org is at API version 51.0 or higher. You can check your org's API version by following the instructions at https://help.salesforce.com/articleView?id=000334996&type=1&mode=1

Thanks

**Comment by gvpatel** [comment]
Hello - I've checked and latest API version is 51.0 in my salesforce org.

It seems one of the main enhancement of this version is upgrade of Spring framework version 

Upgraded versions of log4j (2.14) and Spring framework (5.2.7).

https://stackoverflow.com/questions/40655737/org-xml-sax-saxparseexception-linenumber-10-columnnumber-24-attribute-sing

Does this error is due to change in framework version?

org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 6 in XML document from file [C:\dataloader\v51.0.0\INT\process-conf.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 29; Attribute "singleton" must be declared for element type "bean".


If I run with my older version v49.0.0 of java file its working fine.

**Comment by ashitsalesforce** [comment]
Hi gvpatel,

Perhaps that's the issue. Can you share C:\dataloader\v51.0.0\INT\process-conf.xml from your desktop?

**Comment by ashitsalesforce** [comment]
Hi gvpatel,

I am able to reproduce your issue. You are right in spotting the root-cause: upgrade to Spring 2.x. The fix is to modify the specification of singleton attribute on line 6 of your process-conf.xml from:
singleton="false" 
to
scope="singleton"

**Comment by gvpatel** [comment]
Hello -

I've change  singleton attribute from
singleton="false"
to
scope="singleton"

in both  process-conf.xml and database-conf.xml and its working fine now...

Btw, I'm not seeing logging anymore when I run the process. I'm using log-conf.xml to change log level.  

are there any changes in the logging framework in v51? What do I've to do to see the logs?

**Comment by ashitsalesforce** [comment]
Hi gvpatel,

Good to hear that you are able to successfully run the data loader in CLI mode again. Please capture the first 20 lines of output of the data loader in CLI mode and share your log-conf.xml so that we can try to identify why you are not seeing logging. 

Both log4j and Spring framework are upgraded by a major version in v51 because the older versions of data loader used versions of log4j and Spring framework that are no longer supported, making data loader exposed to potential security vulnerabilities and other bugs. log4j is now at v2.14 and Spring framework is now at 5.2.7.RELEASE.

**Comment by gvpatel** [comment]
Hello - I'm not getting anything in the log. NOTHING....

I've attached 3 files

1) DL_V51.jpg - This for V51
2)log-conf.txt
3)DL_V49.jpg - This is for Version 49. This is FINE.

![DL_V49](https://user-images.githubusercontent.com/18720022/104219148-bc922580-540b-11eb-8f2f-0f11344507c1.jpg)

![DL_V51](https://user-images.githubusercontent.com/18720022/104218767-34138500-540b-11eb-9c61-1d6a01f6b2c0.jpg)
[log-conf.txt](https://github.com/forcedotcom/dataloader/files/5797458/log-conf.txt)

**Comment by ashitsalesforce** [comment]
Hi gvpatel,

Based on your v49 powershell output, your log-conf.xml is in C:\dataloader\v49.0.0\bin\configs folder. Do you have a log-conf.xml in C:\dataloader\v51.0.0\bin\configs folder? Also, it should be similar to the one below due to the log4j upgrade:

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appenders>
    <File name="A1" fileName="${sys:java.io.tmpdir}/sdl.log" append="false">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </File>
    <CONSOLE name="STDOUT" target="SYSTEM_OUT">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </CONSOLE>
  </appenders>
  <loggers>
    <logger name="org.apache.log4j.xml" level="warn">
      <appender-ref ref="A1"/>
      <AppenderRef ref="STDOUT" />
    </logger>
    <logger name="org.apache" level="warn">
      <appender-ref ref="A1"/>
      <AppenderRef ref="STDOUT" />
    </logger>
    <root level="@LOG_LEVEL@">
      <AppenderRef ref="A1"/>
      <AppenderRef ref="STDOUT" />
    </root>
  </loggers>
</configuration>

**Comment by gvpatel** [comment]
Hi - Yes, I do have log-conf.xml under C:\dataloader\v51.0.0\bin\configs folder. I've already attached that file earlier in my previous response. attaching again

Thanks for all your help.

[log-conf.txt](https://github.com/forcedotcom/dataloader/files/5797807/log-conf.txt)

**Comment by ashitsalesforce** [comment]
Thanks gvpatel. Did you copy it from v49.0.0\bin folder? 

Also, I had provided the new sample log-conf.xml file showing the format supported by upgraded log4j version. I am attaching it again.
[log-conf.txt](https://github.com/forcedotcom/dataloader/files/5797904/log-conf.txt)

**Comment by gvpatel** [comment]
No. Actually I copied from C:\dataloader\v51.0.0\configs folder.

Now I've replaced all content from your file BUT still nothing is logged.

**Comment by ashitsalesforce** [comment]
Thanks gvpatel. Can you execute process.bat directly from the command line instead of the powershell script (accountUpsert.ps1) to see if it prompts?

**Comment by gvpatel** [comment]
Hi - I've run process.bat directly and same result....

![DL_V51_cmd](https://user-images.githubusercontent.com/18720022/104233246-8c548200-541f-11eb-9382-2ad1477c3212.jpg)

**Comment by ashitsalesforce** [comment]
Hi gvpatel,

This is a bug introduced during upgrade of log4j. The workaround is to configure LOG4J_CONFIGURATION_FILE environment variable too your log4j config file location (in this case C:\dataloader\v51.0.0\bin\configs\log-conf.xml), launch a new command shell, and run process.bat.

**Comment by gvpatel** [comment]
Hello – This is working fine. Thanks for your help.

Now if you could do me a last favor I would really appreciate.  We’ve started with Spring framework from Oct 2020. This is great a process and it helped us automate entire Salesforce batch load.  There is only one issue that is preventing this from being one of the best 😊. 

We load Account/Contact/Address/Leads/Prospect etc. from our MDM system in salesforce and we’re using Oracle database for MDM. We load all our batch data using databaseRead (key="dataAccess.type" value="databaseRead").  This process does this following

-	Read data from MDM system
-	Update Data in Salesforce
-	Once update is complete this framework download success and failure file using below parameters
                  <entry key="process.outputSuccess" value="C:\dataloader\v51.0.0\INT\Files\status\LNaccountUpsertSuccess.csv"/> 			
                <entry key="process.outputError" value="C:\dataloader\v51.0.0\INT\Files\status\LNaccountUpsertError.csv"/>  

We use failure file to track load errors. We load this data in Salesforce custom object so our support team could fix the data/load errors.

BUT We’re seeing issue while downloading both files in many instances.  

Many time we’re seeing successfully processed records in error file and failed records in success files. We’re seeing this behavior when we use databaseRead (not seeing issue with csvRead). We’ve opened case with Salesforce support (Case #40177856) and its going nowhere.

I also logged issue in git - https://github.com/forcedotcom/dataloader/issues/230

We’ve made sure there are NO data issues (NO invalid Date/Time values) but still facing this issue.

Can you please help us?

Thanks,
Gaurang Patel

**Comment by ashitsalesforce** [comment]
Hi Gaurang,

Good to hear that the workaround has resolved your issue and thanks for reporting the issue regarding load errors. I suggest you work with our support team to get the update.

**Comment by ashitsalesforce** [comment]
p.s. I am closing this thread given that the issue is resolved.
