### ISSUE TITLE
FIELDS() do not work in Dataloader CLI extraction job

### ISSUE THREAD

**Issue by pkozuchowski** [forcedotcom/dataloader#291]
CLI fails when using FIELDS(ALL/STANDARD/CUSTOM) in the SOQL:
```
                <entry key="sfdc.entity" value="Account"/>
                <entry key="sfdc.extractionSOQL"
                        value="select FIELDS(STANDARD) from Account "/>
```

```
2021-07-30 15:34:28,991 INFO  [extract] action.OperationInfo instantiateAction (OperationInfo.java:97) - Instantiating action for operation: extract
2021-07-30 15:34:28,993 INFO  [extract] controller.Controller executeAction (Controller.java:192) - executing operation: extract
2021-07-30 15:34:28,994 INFO  [extract] action.AbstractAction execute (AbstractAction.java:123) - Loading: extract
2021-07-30 15:34:28,995 ERROR [extract] action.AbstractAction handleException (AbstractAction.java:223) - Exception occured during loading
com.salesforce.dataloader.mapping.Mapper$InvalidMappingException: No such field standard on entity Account
        at com.salesforce.dataloader.mapping.SOQLMapper.getSfdcField(SOQLMapper.java:242) ~[dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.evalSfdcField(SOQLMapper.java:233) ~[dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.evalSfdcField(SOQLMapper.java:209) ~[dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.normalizeSoql(SOQLMapper.java:193) ~[dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.addSoqlFieldMapping(SOQLMapper.java:189) ~[dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.initSoqlMapping(SOQLMapper.java:154) ~[dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractExtractAction.getDaoColumns(AbstractExtractAction.java:88) ~[dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractExtractAction.initOperation(AbstractExtractAction.java:139) ~[dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractAction.execute(AbstractAction.java:125) [dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:193) [dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:162) [dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:113) [dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:261) [dataloader-52.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:67) [dataloader-52.0.0-uber.jar:?]
2021-07-30 15:34:28,998 ERROR [extract] progress.NihilistProgressAdapter doneError (NihilistProgressAdapter.java:58) - No such field standard on entity Account

```

**Comment by pgumiela** [comment]
@ashitsalesforce, could we check if this issue still persists?

**Comment by ashitsalesforce** [comment]
Hi @pgumiela , this issue is not addressed as data loader is currently in a strict maintenance mode. We will prioritize this ask when evaluating new features.

**Comment by Domitius** [comment]
I can confirm this is still an issue, DataLoader v54.0
```
<entry key="sfdc.entity" value="User"/>
<entry key="sfdc.extractionSOQL" value="SELECT FIELDS(ALL) FROM User"/>
```
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
15:00:16.375 [getUsers] ERROR com.salesforce.dataloader.action.BulkExtractAction - Exception occured during loading
com.salesforce.dataloader.mapping.Mapper$InvalidMappingException: No such field all on entity User
        at com.salesforce.dataloader.mapping.SOQLMapper.getSfdcField(SOQLMapper.java:242) ~[dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.evalSfdcField(SOQLMapper.java:233) ~[dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.evalSfdcField(SOQLMapper.java:209) ~[dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.normalizeSoql(SOQLMapper.java:193) ~[dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.addSoqlFieldMapping(SOQLMapper.java:189) ~[dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.mapping.SOQLMapper.initSoqlMapping(SOQLMapper.java:154) ~[dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractExtractAction.getDaoColumns(AbstractExtractAction.java:88) ~[dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractExtractAction.initOperation(AbstractExtractAction.java:139) ~[dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.action.AbstractAction.execute(AbstractAction.java:125) [dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:190) [dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:168) [dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:262) [dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:246) [dataloader-54.0.0-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:104) [dataloader-54.0.0-uber.jar:?]
15:00:16.387 [getUsers] ERROR com.salesforce.dataloader.action.progress.NihilistProgressAdapter - No such field all on entity User
```

**Comment by ashitsalesforce** [comment]
This is a feature enhancement request. Data Loader continues to be in a strict maintenance mode. We will consider this along with other when we evaluate new features.
