### ISSUE TITLE
SWT runtime error on Linux - "Unable to find SWT jar for Linux : amd64"

### ISSUE THREAD

**Issue by sirken** [forcedotcom/dataloader#370]
Excited to see work on a Linux build! Been trying to get it working, but no success yet.

Linux Mint 20
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
SWT 4.21

Followed readme build steps (success), extracted contents of dataloader_linux.zip, and ran script:
```
./dataloader.sh
Unable to find SWT jar for Linux : amd64
```

Tried directly and with classpath, same error:
```
java -jar dataloader-53.0.1-uber.jar
Unable to find SWT jar for Linux : amd64

java -cp "swtlinux_x86_64/*" -jar dataloader-53.0.1-uber.jar
Unable to find SWT jar for Linux : amd64
```

Updated SWT to 4.22 using the python script and re-built. New swt files but same error.

Had a java dev take a look, his comments were:

1. The uber jar has no dependency jars in it
2. Using Maven to control the classpath gives the same error
`mvn clean compile -Plinux_x86_64 exec:java -Dexec.mainClass="com.salesforce.dataloader.process.DataLoaderRunner"`

HTH

**Comment by ashitsalesforce** [comment]
Hi @sirken , I have updated DataLoaderRunner.java to handle amd64 arch for linux. Let me know if this works for you.

**Comment by sirken** [comment]
Hi @ashitsalesforce. Yes, it is working now! 🎉 Thank you for the quick update.

**Comment by thomasproductions** [comment]
Having an issue with both 53.0.1 and 53.0.2
Unable to find SWT jar for Windows Server 2019 : amd64
tried similar to previous comment but still won't work.

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions , did you try 53.0.3?

**Comment by thomasproductions** [comment]
due to company policy I am only able to download directly from Salesforce, and Only 53.0.2 is available...

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions , you can set JAVA_TOOL_OPTIONS environment variable to -D"os.arch=x86_64" and see if that fixes your issue.

**Comment by cranney117** [comment]
HI @ashitsalesforce, I was getting a similar error "Unable to find SWT jar for Windows Server 2016 : amd64" and tried your recommendation of adding environment variable JAVA_TOOL_OPTIONS=-D"os.arch=x86_64"
Unfortunately this only changed my error message to "Unable to find SWT jar for Windows Server 2016 : x86_64".

Are there any other potential workarounds for Windows, or would this maybe need to be fixed in a new release of dataloader?

**Comment by thomasproductions** [comment]
same here.. it just changed to error :)

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions , what error does it give now?

**Comment by thomasproductions** [comment]
Unable to find SWT jar for Windows Server 2019 : x86_64

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions and @cranney117,

Data Loader is not certified and supported on Windows Server versions. However, in most cases it should run. I spun up a Windows 2016 Server, installed Data Loader 53.0.2 and OpenJDK JRE 17, and was able to successfully launch it (UI shows up). So, we are at a loss as to why you are running into this issue and it is highly likely that the issue will persist even after upgrading to v53.0.3 because the code that processes os.arch hasn't changed.

To help troubleshoot this further, open log-conf.xml in configs folder and replace line 20:
`    <root level="info">
`
with
`    <root level="debug">
`

Re-run dataloader.bat from command shell, and provide its output.

**Comment by thomasproductions** [comment]
the application will run the UI, that isn't a problem, it's when we launch it from a batch process that this occurs..

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions , I am unable to reproduce the issue on windows server 2016 using data loader v53.0.2 in batch mode. Please provide the command, console output, and logs so that we can troubleshoot this further.

**Comment by thomasproductions** [comment]
Here is the command line
"C:\Program Files\Java\jdk-17.0.1\bin\java.exe" -cp "C:\Program Files\salesforce.com\Data Loader\dataloader-53.0.2-uber.jar;C:\Program Files\salesforce.com\Data Loader\bin\sqljdbc4.jar" -Djava.library.path="C:\Program Files\salesforce.com\Data Loader\bin" -Dsalesforce.config.dir="c:\ApexDataLoader\data1\conf" com.salesforce.dataloader.process.DataLoaderRunner process.name=extractSomeIDsProcess  1>>LogFile.txt

**Comment by ashitsalesforce** [comment]
Hi @thomasproductions , add 'run.mode=batch' to the command and retry. For example,

`"C:\Program Files\Java\jdk-17.0.1\bin\java.exe" -cp "C:\Program Files\salesforce.com\Data Loader\dataloader-53.0.2-uber.jar;C:\Program Files\salesforce.com\Data Loader\bin\sqljdbc4.jar" -Djava.library.path="C:\Program Files\salesforce.com\Data Loader\bin" run.mode=batch -Dsalesforce.config.dir="c:\ApexDataLoader\data1\conf" com.salesforce.dataloader.process.DataLoaderRunner process.name=extractSomeIDsProcess 1>>LogFile.txt`

Also, out of curiosity, 
- why C:\Program Files\salesforce.com\Data Loader\bin\sqljdbc4.jar is specified in classpath? 
- why specify java.library.path option?

Wondering if not specifying these is causing any issues for you.

**Comment by pa1codehub** [comment]
> Hi @thomasproductions , you can set JAVA_TOOL_OPTIONS environment variable to -D"os.arch=x86_64" and see if that fixes your issue.

Hi @ashitsalesforce.
I'm seeing the same issue in the Linux environment. I have downloaded the V53.0.3 release. How to override the SWT path that 
DataLoaderRunner.java is looking for?

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , did you build data loader for Linux from the repo?

**Comment by pa1codehub** [comment]
> Hi @pa1codehub , did you build data loader for Linux from the repo?

Thanks for the response, @ashitsalesforce. No, I'm using a different repo built based on your dataloader-46.0.0-uber.jar version.
Here is the link: https://github.com/mhamzas/Scripted-Data-Loader-for-Mac-Unix

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , you need to contact that repo's owner about your issue. I would suggest using the official data loader repo and build it using dlbuilder.sh script.

**Comment by thomasproductions** [comment]
> Hi @thomasproductions , you can set JAVA_TOOL_OPTIONS environment variable to -D"os.arch=x86_64" and see if that fixes your issue.
hi ashitsalesforce, wanted to let you know that I have everything sussed.. adding the run.mode=batch did help. this is a system that I inherited and apparently hadn't been upgraded in quite a while. took me a couple of days to actually get it to run partially, then adding run.mode=batch solved the remaining error ..

thanks

**Comment by pa1codehub** [comment]
Hi @ashitsalesforce,
My issue is similar to what jschlicht experienced in the issue: https://github.com/forcedotcom/dataloader/issues/365.
"Previously, I didn't need to have the SWT libraries on the system at all to run the dataloader in batch mode. It never tried to load SWT at all. "
I'm using dataloader-46.0.0-uber.jar version to run the dataloader (as a totally command line application) in Linux. Updated the jar to latest version and below is the command we are using, 

**$JAVA -cp dataloader-54.0.0-uber.jar -Dsalesforce.config.dir=$CONF_DIR com.salesforce.dataloader.process.DataLoaderRunner process.name=$PROCESS > /apps/sdl/data/"$1".OutPut."$now".log**

Is there a workaround to resolve the "Unable to find SWT jar for Linux : amd64" error without using the dlbuilder.sh? 
Please let me know your thoughts.

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , try the following command:
`java -jar dataloader-54.0.0-uber.jar run.mode=batch salesforce.config.dir=$CONF_DIR process.name=$PROCESS > /apps/sdl/data/"$1".OutPut."$now".log`

**Comment by pa1codehub** [comment]
Thanks, @ashitsalesforce. The good part is now seeing a different error. Below is the error,

I referred to this issue and updated singleton="false" to scope="singleton" in process-conf.xml but still seeing the error [240](https://github.com/forcedotcom/dataloader/issues/240)

`18:46:26.947 [main] ERROR com.salesforce.dataloader.process.ProcessConfig - Error loading process: csvFacilityExtractProcess configuration from config file: /apps/sdl/conf/process-conf.xml
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 5 in XML document from URL [file:/apps/sdl/conf/process-conf.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 29; Attribute "singleton" must be declared for element type "bean".
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:402) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:338) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:257) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:671) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getBeanFactory(ProcessConfig.java:112) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:94) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:301) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:256) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:246) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:104) [dataloader-54.0.0-uber.jar:?]
Caused by: org.xml.sax.SAXParseException: Attribute "singleton" must be declared for element type "bean".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204) ~[?:?]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.addDTDDefaultAttrsAndValidate(XMLDTDValidator.java:1237) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleStartElement(XMLDTDValidator.java:1846) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:728) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1397) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:77) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:432) ~[dataloader-54.0.0-uber.jar:?]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390) ~[dataloader-54.0.0-uber.jar:?]
	... 19 more
18:46:26.966 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Failed to create process
com.salesforce.dataloader.exception.ProcessInitializationException: Error loading process: csvFacilityExtractProcess configuration from config file: /apps/sdl/conf/process-conf.xml
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:98) ~[dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:301) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:256) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:246) [dataloader-54.0.0-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:104) [dataloader-54.0.0-uber.jar:?]`

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , share the content of your process-xml to help troubleshoot this issue. Remove personal or business information in the properties before sharing such as sfdc.username, sfdc.password.

**Comment by pa1codehub** [comment]
Hi @ashitsalesforce,
It is working fine, I need to update `scope="singleton"` for all the beans in the process-conf.xml which I was not doing earlier. 
The only issue I see is log file is getting overridden on the previous file as below, 
 
`[WSC][DataLoaderRunner.main:104]Log file already exists, appending to status/sfdcSoapTrace.log`

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , good to hear that your issues are addressed. Regarding your logging issue, you may need to tweak your log-conf.xml in the configuration directory (specified in $CONF_DIR variable). Here is the default log-conf.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appenders>
    <File name="fileAppender" fileName="${sys:java.io.tmpdir}/sdl.log" append="true">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </File>
    <CONSOLE name="STDOUT" target="SYSTEM_OUT">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </CONSOLE>
  </appenders>
  <loggers>
    <logger name="org.apache.log4j.xml" level="warn">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </logger>
    <logger name="org.apache" level="warn">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </logger>
    <root level="info">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </root>
  </loggers>
</configuration>
```

**Comment by pa1codehub** [comment]
@ashitsalesforce - As I inherited this code so not sure why we are not using the log-conf.xml. We are creating the log files using the `/apps/sdl/data/"$1".OutPut."$now".log` on every run. ($1 is the bean id  from process-conf.xml)

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , log output file is different from log4j config file. What does the console output show when you run java command? Does it output a line such as `INFO  [main] controller.Controller initLog (Controller.java:532) - Using log4j2 configuration file at location: /Users/<my username>/dataloader/configs/log-conf.xml`? or does it have a line such as `[main] ERROR com.salesforce.dataloader.controller.Controller - Unable to initialize logging`?

**Comment by pa1codehub** [comment]
Hi @ashitsalesforce,
after running the java command - I do not see any console output (attached the file) 
![dataloader_run](https://user-images.githubusercontent.com/22842007/151106673-4075a57c-c700-441e-b27b-439436607665.PNG)

Below is the only output I see in the output log file.
`[WSC][DataLoaderRunner.main:104]Log file already exists, appending to status/sfdcSoapTrace.log`

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , it is very likely that a log-conf.xml exists on your system and it specifies log level at "warn" or "error". Check if an environment variable, LOG4J_CONFIGURATION_FILE, is set and if so, look at the log file specified in its value.

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , also, what is the content of process.sh?

**Comment by pa1codehub** [comment]
Hi @ashitsalesforce ,
I checked all the environment variables but didn't see anything related to LOG4J or JAVA_TOOL_OPTIONS. We have a variable with LOGNAME.

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub, please provide the content of process.sh.

**Comment by pa1codehub** [comment]
> Hi @pa1codehub, please provide the content of process.sh.
Please find the file in my above response.

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , your config directory is specified as "./conf" (value of $CONF_DIR variable). Can you look for log-conf.xml in that directory?

**Comment by pa1codehub** [comment]
Hi @ashitsalesforce ,
we have process-confg.xml, config.properties and other .sdl files in the ./config folder but not the log-config.xml file.

**Comment by ashitsalesforce** [comment]
hi @pa1codehub , 

The output `Log file already exists, appending to status/sfdcSoapTrace.log` means Data Loader has been appending to, not overwriting, sfdcSoapTrace.log file in status directory. Look at it to make sure previous runs' output is not overwritten.

If you want to change the logging configuration, try the following:
- Create log-conf.xml in your ./conf directory using the [default in the github repo](https://github.com/forcedotcom/dataloader/blob/master/release/configs/log-conf.xml).
- Set the environment variable LOG4J_CONFIGURATION_FILE in process.sh as `set LOG4J_CONFIGURATION_FILE=./conf/log-conf.xml` before java command is invoked. Alternately, set it in the interactive shell before running process.sh.
- Once you see some log output when running process.sh, you can tweak logging configuration in log-conf.xml to your needs. Refer to log4j documentation for how to do so.

**Comment by pa1codehub** [comment]
> hi @pa1codehub ,
> 
> The output `Log file already exists, appending to status/sfdcSoapTrace.log` means Data Loader has been appending to, not overwriting, sfdcSoapTrace.log file in status directory. Look at it to make sure previous runs' output is not overwritten.
> 
> If you want to change the logging configuration, try the following:
> 
> * Create log-conf.xml in your ./conf directory using the [default in the github repo](https://github.com/forcedotcom/dataloader/blob/master/release/configs/log-conf.xml).
> * Set the environment variable LOG4J_CONFIGURATION_FILE in process.sh as `set LOG4J_CONFIGURATION_FILE=./conf/log-conf.xml` before java command is invoked. Alternately, set it in the interactive shell before running process.sh.
> * Once you see some log output when running process.sh, you can tweak logging configuration in log-conf.xml to your needs. Refer to log4j documentation for how to do so.

Hi @ashitsalesforce,

I'll try adding the logging configuration as per the listed steps above. But I'm trying to understand what has changed from the previous data loader version because we use to get the below output in the console after running the java command using dataloader-46.0.0-uber.jar

`2022-01-25 23:07:18,380 INFO  [main] controller.Controller initLog (Controller.java:475) - Using built-in logging configuration, no log-conf.xml in /apps/sdl/configs/log-conf.xml
2022-01-25 23:07:18,396 INFO  [main] controller.Controller initLog (Controller.java:477) - The log has been initialized
2022-01-25 23:07:18,400 INFO  [main] process.ProcessConfig getBeanFactory (ProcessConfig.java:104) - Loading process configuration from config file: /apps/sdl/conf/process-conf.xml
2022-01-25 23:07:18,481 INFO  [main] support.AbstractApplicationContext prepareRefresh (AbstractApplicationContext.java:495) - Refreshing org.springframework.context.support.FileSystemXmlApplicationContext@4b5d6a01: startup date [Tue Jan 25 23:07:18 CST 2022]; root of context hierarchy
2022-01-25 23:07:18,532 INFO  [main] xml.XmlBeanDefinitionReader loadBeanDefinitions (XmlBeanDefinitionReader.java:315) - Loading XML bean definitions from URL [file:/apps/sdl/conf/process-conf.xml]
2022-01-25 23:07:18,589 INFO  [main] support.DefaultListableBeanFactory preInstantiateSingletons (DefaultListableBeanFactory.java:557) - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@152aa092: defining beans [************Process,************Process,************Process,************Process]; root of factory hierarchy
2022-01-25 23:07:18,634 INFO  [***********Extract] controller.Controller createDir (Controller.java:306) - Config directory already exists: conf
2022-01-25 23:07:18,634 INFO  [***********Extract] controller.Controller initConfig (Controller.java:396) - Looking for file in config path: /apps/sdl/conf/config.properties
2022-01-25 23:07:18,635 INFO  [***********Extract] controller.Controller initConfig (Controller.java:429) - User config is found in /apps/sdl/conf/config.properties
2022-01-25 23:07:18,694 INFO  [***********Extract] controller.Controller initConfig (Controller.java:439) - The controller config has been initialized
2022-01-25 23:07:18,696 INFO  [***********Extract] process.ProcessRunner run (ProcessRunner.java:123) - Initializing process engine
2022-01-25 23:07:18,696 INFO  [***********Extract] process.ProcessRunner run (ProcessRunner.java:126) - Loading parameters
2022-01-25 23:07:18,708 INFO  [***********Extract] process.ProcessRunner run (ProcessRunner.java:134) - Logging in to: ********************
2022-01-25 23:07:18,714 INFO  [***********Extract] client.PartnerClient login (PartnerClient.java:500) - Beginning Partner Salesforce login ....`

**Comment by ashitsalesforce** [comment]
Hi @pa1codehub , some of the major changes between v46 and v53 have been upgrades of open source utilities data loader uses including log4j, Spring, SWT. In your case it is likely that the upgrade from log4j 1.x to 2.x is resulting in the change of behavior. Our recommendation would be to use log-conf.xml provided in the github repo going forward.

**Comment by pa1codehub** [comment]
Hi @ashitsalesforce,
Thank you. It worked fine after adding the log-confg.xml file from the repo.
