### ISSUE TITLE
[BatchMode] Password is decrypted twice when provided as a CLI argument

### ISSUE THREAD

**Issue by KThompso** [forcedotcom/dataloader#393]
## Overview

When executing a dataloader process in batch mode and providing the `sfdc.password` parameter as an argument on the command line, I receive an error `java.security.GeneralSecurityException: Error to decrypt message`.  Dataloader appears to be attempting to decrypt the password twice.  When the encrypted password is encrypted a second time, the login succeeds.  Also, a portion of the plaintext password is leaked to the log.

This does not occur when the encrypted password is defined in the `process-conf.xml` file in the `configOverrideMap` section.

### Expected Behavior

Dataloader should decrypt the password and execute the process.

### Observed Behavior

Receive an error message from the encryption utility.

## Environment

- **OS**: linux debian 10 [docker container]
- **Java**: openjdk version "11.0.13" 2021-10-19
- **Dataloader**: v53.0.2

## Reproduction Steps

1. Encrypt a password using the dataloader encryption utility.
2. Execute a dataloader process, passing the `sfdc.password` parameter in from the command line.  e.g. `dataloader.sh mode=batch process.name=myProcessName sfdc.password=<encrypted-password>`

## Workaround

Encrypt the password twice (once on the plaintext password, and a second time on the ciphertext output).  Then dataloader appears to work correctly as the password is passed through the decryption utility twice.

Also providing `sfdc.password` in the `process-conf.xml` file does not appear to be impacted by the same issue.

## Error message

*Note*: password here was "fakepass" running the process "csvAccountExtract" from the configuration samples.

```
23:31:47.879 [csvAccountExtract] ERROR com.salesforce.dataloader.security.EncryptionAesUtil - Fail to decrypt message: For input string: "ke"
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
23:31:47.883 [csvAccountExtract] ERROR com.salesforce.dataloader.config.Config - Error loading parameter: sfdc.password of type: java.lang.String
java.security.GeneralSecurityException: Error to decrypt message: 
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:218) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:807) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:769) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:758) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:787) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:117) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:272) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:108) [dataloader-53.0.2-uber.jar:?]
Caused by: java.lang.NumberFormatException: For input string: "ke"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:957) ~[?:?]
        at java.lang.Integer.decode(Integer.java:1436) ~[?:?]
        at com.salesforce.dataloader.security.EncryptionUtil.textToBytes(EncryptionUtil.java:40) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:214) ~[dataloader-53.0.2-uber.jar:?]
        ... 8 more
23:31:47.900 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process csvAccountExtract
java.lang.RuntimeException: com.salesforce.dataloader.exception.ParameterLoadException: Error loading parameter: sfdc.password of type: java.lang.String
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:182) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:117) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:272) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:108) [dataloader-53.0.2-uber.jar:?]
Caused by: com.salesforce.dataloader.exception.ParameterLoadException: Error loading parameter: sfdc.password of type: java.lang.String
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:814) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:769) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:758) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:787) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
Caused by: java.security.GeneralSecurityException: Error to decrypt message: 
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:218) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:807) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:769) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:758) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:787) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
Caused by: java.lang.NumberFormatException: For input string: "ke"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:957) ~[?:?]
        at java.lang.Integer.decode(Integer.java:1436) ~[?:?]
        at com.salesforce.dataloader.security.EncryptionUtil.textToBytes(EncryptionUtil.java:40) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:214) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:807) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:769) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:758) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:787) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
```

**Comment by ashitsalesforce** [comment]
Hi @KThompso , thanks for catching this issue and also providing 2 workarounds. I am attaching a fix. Let us know if that addresses the issue.

MD5 (dataloader_mac.zip) = 3161077d437d6126ee491301b006f752
MD5 (dataloader_win.zip) = 04d3a8c0acd17432c7c8047281cf8947

[dataloader_mac.zip](https://github.com/forcedotcom/dataloader/files/7783205/dataloader_mac.zip)
[dataloader_win.zip](https://github.com/forcedotcom/dataloader/files/7783226/dataloader_win.zip)

**Comment by kthompsonbass-btig** [comment]
Hi @ashitsalesforce, thanks for the quick response.  I tested the windows version but still receive the same error.  See below.

```
$ ./run-proc.sh 
#!/bin/bash

cat $0 ; echo

export PATH="/c/Program Files/Java/jdk-17.0.1/bin:$PATH"

PASS=9be8156cf54474ef58aa0b1ae9d14e98de2b81f13955cf93213e42e70f352dc5
USER=fake.user@example.com
URL=https://test.salesforce.com/

set -x

# show decrypted password
java -cp dataloader-53.0.2-uber.jar \
    com.salesforce.dataloader.security.EncryptionUtil \
    -d "$PASS" "$PWD/dataLoader.key"; echo

# execute sample process
java -jar dataloader-53.0.2-uber.jar \
        "run.mode=batch" \
        "sfdc.username=$USER" \
        "sfdc.password=$PASS" \
        "sfdc.endpoint=$URL" \
        "salesforce.config.dir=$PWD" \
        "process.encryptionKeyFile=$PWD/dataLoader.key" \
        "process.name=sampleAccountExtract" \
        "dataAccess.name=$PWD/accounts.csv"

+ java -cp dataloader-53.0.2-uber.jar com.salesforce.dataloader.security.EncryptionUtil -d 9be8156cf54474ef58aa0b1ae9d14e98de2b81f13955cf93213e42e70f352dc5 /c/Users/kthompso/projects/dataloader/dataLoader.key
The output string of decryption is: 
fakepass
+ echo

+ java -jar dataloader-53.0.2-uber.jar run.mode=batch sfdc.username=fake.user@example.com sfdc.password=9be8156cf54474ef58aa0b1ae9d14e98de2b81f13955cf93213e42e70f352dc5 sfdc.endpoint=https://test.salesforce.com/ salesforce.config.dir=/c/Users/kthompso/projects/dataloader process.encryptionKeyFile=/c/Users/kthompso/projects/dataloader/dataLoader.key process.name=sampleAccountExtract dataAccess.name=/c/Users/kthompso/projects/dataloader/accounts.csv
08:24:18.496 [sampleAccountExtract] ERROR com.salesforce.dataloader.security.EncryptionAesUtil - Fail to decrypt message: For input string: "ke" under radix 16
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
08:24:18.502 [sampleAccountExtract] ERROR com.salesforce.dataloader.config.Config - Error loading parameter: sfdc.password of type: java.lang.String
java.security.GeneralSecurityException: Error to decrypt message:
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:218) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:817) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:776) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:759) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:797) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:117) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:272) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:108) [dataloader-53.0.2-uber.jar:?]
Caused by: java.lang.NumberFormatException: For input string: "ke" under radix 16
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:973) ~[?:?]
        at java.lang.Integer.decode(Integer.java:1458) ~[?:?]
        at com.salesforce.dataloader.security.EncryptionUtil.textToBytes(EncryptionUtil.java:40) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:214) ~[dataloader-53.0.2-uber.jar:?]
        ... 8 more
08:24:18.583 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process sampleAccountExtract
java.lang.RuntimeException: com.salesforce.dataloader.exception.ParameterLoadException: Error loading parameter: sfdc.password of type: java.lang.String
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:182) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:117) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:272) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:108) [dataloader-53.0.2-uber.jar:?]
Caused by: com.salesforce.dataloader.exception.ParameterLoadException: Error loading parameter: sfdc.password of type: java.lang.String
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:824) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:776) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:759) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:797) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
Caused by: java.security.GeneralSecurityException: Error to decrypt message:
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:218) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:817) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:776) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:759) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:797) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
Caused by: java.lang.NumberFormatException: For input string: "ke" under radix 16
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:973) ~[?:?]
        at java.lang.Integer.decode(Integer.java:1458) ~[?:?]
        at com.salesforce.dataloader.security.EncryptionUtil.textToBytes(EncryptionUtil.java:40) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:214) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:817) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:776) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:759) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:797) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
```

Here is the key and process-conf.xml I used:
```
$ base64 dataLoader.key
CA4rIvgH7ZHEGBaP9He40g==
$ cat process-conf.xml
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
    <bean id="sampleAccountExtract"
          class="com.salesforce.dataloader.process.ProcessRunner"
          scope="prototype">
      <description>sampleAccountExtract job gets account info from salesforce and saves info into a CSV file."</description>
        <property name="name" value="sampleAccountExtract"/>
        <property name="configOverrideMap">
            <map>
                <entry key="sfdc.entity" value="Account"/>
                <entry key="sfdc.extractionSOQL" value="Select Id FROM Account LIMIT 1"/>
                <entry key="process.operation" value="extract"/>
                <entry key="dataAccess.type" value="csvWrite"/>
            </map>
        </property>
    </bean>
</beans>
```

If I encrypt the password a second time, it decrypts the password correctly.  Let me know if I can provide any more information.

**Comment by KThompso** [comment]
Hi @ashitsalesforce, thanks for the quick response.  I tested the windows version but still receive the same error.  See below.

```
$ ./run-proc.sh 
#!/bin/bash

cat $0 ; echo

export PATH="/c/Program Files/Java/jdk-17.0.1/bin:$PATH"

PASS=9be8156cf54474ef58aa0b1ae9d14e98de2b81f13955cf93213e42e70f352dc5
USER=fake.user@example.com
URL=https://test.salesforce.com/

set -x

# show decrypted password
java -cp dataloader-53.0.2-uber.jar \
    com.salesforce.dataloader.security.EncryptionUtil \
    -d "$PASS" "$PWD/dataLoader.key"; echo

# execute sample process
java -jar dataloader-53.0.2-uber.jar \
        "run.mode=batch" \
        "sfdc.username=$USER" \
        "sfdc.password=$PASS" \
        "sfdc.endpoint=$URL" \
        "salesforce.config.dir=$PWD" \
        "process.encryptionKeyFile=$PWD/dataLoader.key" \
        "process.name=sampleAccountExtract" \
        "dataAccess.name=$PWD/accounts.csv"

+ java -cp dataloader-53.0.2-uber.jar com.salesforce.dataloader.security.EncryptionUtil -d 9be8156cf54474ef58aa0b1ae9d14e98de2b81f13955cf93213e42e70f352dc5 /c/Users/kthompso/projects/dataloader/dataLoader.key
The output string of decryption is: 
fakepass
+ echo

+ java -jar dataloader-53.0.2-uber.jar run.mode=batch sfdc.username=fake.user@example.com sfdc.password=9be8156cf54474ef58aa0b1ae9d14e98de2b81f13955cf93213e42e70f352dc5 sfdc.endpoint=https://test.salesforce.com/ salesforce.config.dir=/c/Users/kthompso/projects/dataloader process.encryptionKeyFile=/c/Users/kthompso/projects/dataloader/dataLoader.key process.name=sampleAccountExtract dataAccess.name=/c/Users/kthompso/projects/dataloader/accounts.csv
08:24:18.496 [sampleAccountExtract] ERROR com.salesforce.dataloader.security.EncryptionAesUtil - Fail to decrypt message: For input string: "ke" under radix 16
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
08:24:18.502 [sampleAccountExtract] ERROR com.salesforce.dataloader.config.Config - Error loading parameter: sfdc.password of type: java.lang.String
java.security.GeneralSecurityException: Error to decrypt message:
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:218) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:817) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:776) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:759) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:797) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:117) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:272) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:108) [dataloader-53.0.2-uber.jar:?]
Caused by: java.lang.NumberFormatException: For input string: "ke" under radix 16
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:973) ~[?:?]
        at java.lang.Integer.decode(Integer.java:1458) ~[?:?]
        at com.salesforce.dataloader.security.EncryptionUtil.textToBytes(EncryptionUtil.java:40) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:214) ~[dataloader-53.0.2-uber.jar:?]
        ... 8 more
08:24:18.583 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process sampleAccountExtract
java.lang.RuntimeException: com.salesforce.dataloader.exception.ParameterLoadException: Error loading parameter: sfdc.password of type: java.lang.String
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:182) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:117) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:272) [dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:108) [dataloader-53.0.2-uber.jar:?]
Caused by: com.salesforce.dataloader.exception.ParameterLoadException: Error loading parameter: sfdc.password of type: java.lang.String
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:824) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:776) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:759) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:797) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
Caused by: java.security.GeneralSecurityException: Error to decrypt message:
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:218) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:817) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:776) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:759) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:797) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
Caused by: java.lang.NumberFormatException: For input string: "ke" under radix 16
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.valueOf(Integer.java:973) ~[?:?]
        at java.lang.Integer.decode(Integer.java:1458) ~[?:?]
        at com.salesforce.dataloader.security.EncryptionUtil.textToBytes(EncryptionUtil.java:40) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.security.EncryptionAesUtil.decryptMsg(EncryptionAesUtil.java:214) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptProperty(Config.java:817) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.decryptPasswordProperty(Config.java:776) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.postLoad(Config.java:759) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.config.Config.loadParameterOverrides(Config.java:797) ~[dataloader-53.0.2-uber.jar:?]
        at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137) ~[dataloader-53.0.2-uber.jar:?]
        ... 3 more
```

Here is the key and process-conf.xml I used:
```
$ base64 dataLoader.key
CA4rIvgH7ZHEGBaP9He40g==
$ cat process-conf.xml
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
    <bean id="sampleAccountExtract"
          class="com.salesforce.dataloader.process.ProcessRunner"
          scope="prototype">
      <description>sampleAccountExtract job gets account info from salesforce and saves info into a CSV file."</description>
        <property name="name" value="sampleAccountExtract"/>
        <property name="configOverrideMap">
            <map>
                <entry key="sfdc.entity" value="Account"/>
                <entry key="sfdc.extractionSOQL" value="Select Id FROM Account LIMIT 1"/>
                <entry key="process.operation" value="extract"/>
                <entry key="dataAccess.type" value="csvWrite"/>
            </map>
        </property>
    </bean>
</beans>
```

If I encrypt the password a second time, it decrypts the password correctly.  Let me know if I can provide any more information.

**Comment by ashitsalesforce** [comment]
Hi @KThompso , thanks for trying it out. We will troubleshoot this further and get back to you.

**Comment by ashitsalesforce** [comment]
Hi @KThompso , here is a patch that should fix the issue.
MD5 (dataloader_mac.zip) = 0134ca8ea369f429eaf68cbdf962afd6
MD5 (dataloader_win.zip) = 2a73b19cbcc3ba5d91c05783055a2b03

[dataloader_mac.zip](https://github.com/forcedotcom/dataloader/files/7786709/dataloader_mac.zip)
[dataloader_win.zip](https://github.com/forcedotcom/dataloader/files/7786711/dataloader_win.zip)

You can unzip one of these and use the uber jar (dataloader-53.0.2-uber.jar) on linux because the jar file is identical for all platforms.

**Comment by KThompso** [comment]
Looks good to me!  Thank you very much for the support. 👍 👍

Just as a note, it appears that it's now possible to use a plaintext password provided you also define `sfdc.password.decrypted` and they match.  E.g.

```
java -jar dataloader-53.0.2-uber.jar \
    run.mode=batch \
    process.name=someProcess \
    sfdc.username=user@example.com \
    sfdc.password=myPlaintextPassword \
    sfdc.password.decrypted=myPlaintextPassword
```

**Comment by ashitsalesforce** [comment]
Hi @KThompso , thanks for confirming the fix. We do not support the use of plaintext password. So, do not rely on that property.
