### ISSUE TITLE
java.lang.ClassCastException: class com.salesforce.dataloader.ui.extraction.ExtractionSOQLPage cannot be cast to class com.salesforce.dataloader.ui.extraction.ExtractionFinishPage

### ISSUE THREAD

**Issue by matinlotfali** [forcedotcom/dataloader#494]
I am getting the following error when trying to Export.

```
java.lang.ClassCastException: class com.salesforce.dataloader.ui.extraction.ExtractionSOQLPage cannot be cast to class com.salesforce.dataloader.ui.extraction.ExtractionFinishPage (com.salesforce.dataloader.ui.extraction.ExtractionSOQLPage and com.salesforce.dataloader.ui.extraction.ExtractionFinishPage are in unnamed module of loader 'app')
	at com.salesforce.dataloader.ui.extraction.ExtractionWizard.getFinishPage(ExtractionWizard.java:79)
	at com.salesforce.dataloader.ui.extraction.ExtractionWizard.performFinish(ExtractionWizard.java:128)
	at com.salesforce.dataloader.ui.LoaderWizardDialog.finishPressed(LoaderWizardDialog.java:650)
	at com.salesforce.dataloader.ui.LoaderWizardDialog.buttonPressed(LoaderWizardDialog.java:314)
	at com.salesforce.dataloader.ui.LoaderWizardDialog$5.widgetSelected(LoaderWizardDialog.java:1259)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.salesforce.dataloader.ui.uiActions.OperationUIAction.run(OperationUIAction.java:54)
	at com.salesforce.dataloader.ui.LoaderWindow$2.widgetSelected(LoaderWindow.java:257)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.salesforce.dataloader.ui.LoaderWindow.run(LoaderWindow.java:147)
	at com.salesforce.dataloader.controller.Controller.createAndShowGUI(Controller.java:305)
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:121)
```

I am using Fedora 36 and here is my Java version:

```
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)
```

**Comment by ashitsalesforce** [comment]
Hi @matinlotfali , I doubt that this is JDK/JRE issue. Which version of data loader are you using? If you built it by cloning the repo, when did you clone? See if the issue persists after syncing to the latest in the repo.

**Comment by matinlotfali** [comment]
I cloned right now

**Comment by ashitsalesforce** [comment]
Did that fix the issue? If not, what's the log output?

**Comment by matinlotfali** [comment]
It did not. Here is the output:

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-06-22 17:17:40,467 INFO  [main] controller.Controller initLog (Controller.java:506) - The log has been initialized
2022-06-22 17:17:40,478 INFO  [main] controller.Controller createDir (Controller.java:363) - Config directory already exists: /home/matin/Git/MistyWest/dataloader/target/configs
2022-06-22 17:17:40,479 INFO  [main] controller.Controller initConfig (Controller.java:399) - Looking for file in config path: /home/matin/Git/MistyWest/dataloader/target/configs/config.properties
2022-06-22 17:17:40,570 INFO  [main] config.LastRun load (LastRun.java:97) - Last run info will be saved in file: /home/matin/Git/MistyWest/dataloader/target/configs/ui_lastRun.properties
2022-06-22 17:17:40,572 INFO  [main] controller.Controller initConfig (Controller.java:433) - The controller config has been initialized
2022-06-22 17:17:41,006 INFO  [main] config.LastRun load (LastRun.java:97) - Last run info will be saved in file: /home/matin/Git/MistyWest/dataloader/target/configs/ui_lastRun.properties
2022-06-22 17:17:41,553 INFO  [main] action.OperationInfoUIHelper instantiateWizard (OperationInfoUIHelper.java:111) - !OperationInfoUIHelper.creatingWizard!
2022-06-22 17:17:44,187 INFO  [main] action.OperationInfoUIHelper instantiateWizard (OperationInfoUIHelper.java:111) - !OperationInfoUIHelper.creatingWizard!
Opening in existing browser session.
failed to open /usr/lib64/dri/hybrid_drv_video.so
2022-06-22 17:18:14,358 INFO  [main] client.PartnerClient login (PartnerClient.java:549) - Beginning Partner Salesforce login ....
2022-06-22 17:18:14,413 INFO  [main] client.PartnerClient setConfiguredSessionId (PartnerClient.java:585) - Using manually configured session id to bypass login
2022-06-22 17:18:34,803 INFO  [main] dao.DataAccessObjectFactory getDaoInstance (DataAccessObjectFactory.java:52) - Instantiating data access object: extract.csv of type: csvWrite
java.lang.ClassCastException: class com.salesforce.dataloader.ui.extraction.ExtractionSOQLPage cannot be cast to class com.salesforce.dataloader.ui.extraction.ExtractionFinishPage (com.salesforce.dataloader.ui.extraction.ExtractionSOQLPage and com.salesforce.dataloader.ui.extraction.ExtractionFinishPage are in unnamed module of loader 'app')
	at com.salesforce.dataloader.ui.extraction.ExtractionWizard.getFinishPage(ExtractionWizard.java:79)
	at com.salesforce.dataloader.ui.extraction.ExtractionWizard.performFinish(ExtractionWizard.java:128)
	at com.salesforce.dataloader.ui.LoaderWizardDialog.finishPressed(LoaderWizardDialog.java:650)
	at com.salesforce.dataloader.ui.LoaderWizardDialog.buttonPressed(LoaderWizardDialog.java:314)
	at com.salesforce.dataloader.ui.LoaderWizardDialog$5.widgetSelected(LoaderWizardDialog.java:1259)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.salesforce.dataloader.ui.uiActions.OperationUIAction.run(OperationUIAction.java:54)
	at com.salesforce.dataloader.ui.LoaderWindow$2.widgetSelected(LoaderWindow.java:257)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.salesforce.dataloader.ui.LoaderWindow.run(LoaderWindow.java:147)
	at com.salesforce.dataloader.controller.Controller.createAndShowGUI(Controller.java:305)
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:121)
```

**Comment by matinlotfali** [comment]
Fixed the issue myself.

**Comment by ashitsalesforce** [comment]
Thanks @matinlotfali . While the fix is correct, I will reject this PR as I plan to do a PR shortly containing this fix and a fix to not enable "Next" button on the Edit SoQL page if it happens to be the last page. I am also checking in minor version updates for a few components.

**Comment by ashitsalesforce** [comment]
Hi @matinlotfali , thanks for reporting the issue and helping pinpoint the root-cause as well as providing a candidate fix. I have checked in the fix and am closing the issue.
