### ISSUE TITLE
Upsert from Database using Parent\:fieldname mapping throws index out of range

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#56]
Trying to automate a migration from Oracle to Salesforce.  database-conf.xml and process-conf.xml all seem dandy, as does the mapping for CaseComment.  30.0 GUI operates fine, but the command line crashes.

2015-03-25 17:19:39,052 INFO  [importCaseComment] process.ProcessRunner run (ProcessRunner.java:132) - Checking the data access object connection
2015-03-25 17:19:39,373 INFO  [importCaseComment] process.ProcessRunner run (ProcessRunner.java:137) - Setting field types
2015-03-25 17:19:39,730 INFO  [importCaseComment] process.ProcessRunner run (ProcessRunner.java:141) - Setting object reference types
2015-03-25 17:19:40,402 INFO  [importCaseComment] process.ProcessRunner run (ProcessRunner.java:145) - Creating Map
2015-03-25 17:19:40,403 INFO  [importCaseComment] action.OperationInfo instantiateAction (OperationInfo.java:95) - Instantiating action for operation: upsert
2015-03-25 17:19:40,435 INFO  [importCaseComment] controller.Controller executeAction (Controller.java:120) - executing operation: upsert
2015-03-25 17:19:40,436 INFO  [importCaseComment] action.AbstractAction execute (AbstractAction.java:120) - Loading: upsert
2015-03-25 17:19:40,651 ERROR [importCaseComment] action.AbstractAction handleException (AbstractAction.java:204) - Exception occured during loading
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.get(LinkedList.java:476)
	at com.salesforce.dataloader.action.AbstractAction.openSuccessWriter(AbstractAction.java:250)
	at com.salesforce.dataloader.action.AbstractAction.execute(AbstractAction.java:125)
	at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:121)
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:149)
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:100)
	at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:253)
2015-03-25 17:19:40,654 ERROR [importCaseComment] progress.NihilistProgressAdapter doneError (NihilistProgressAdapter.java:58) - Index: 0, Size: 0

**Comment by tggagne** [comment]
I should note both the GUI and the command line work when the input is a CSV file.  But if I change the input to a datasource, it freaks out.

**Comment by tggagne** [comment]
Ok.  I just discovered this works fine if I add the columns property with matching values.

**Comment by mamiao26536** [comment]
Hi @tggagne  
I had face the problem that list above and I try to find out the solution. I don't know how can I sovle these problem. My error return like this "ERROR [importCaseComment] action.AbstractAction handleException (AbstractAction.java:204) - Exception occured during loading"
and (AbstractAction.java:332). so could you please tell me about your solution.

Please & Thank you so much for your help.
Jittramas.K
