### ISSUE TITLE
Data loader - Spring Framework - Database driver issue

### ISSUE THREAD

**Issue by gvpatel** [forcedotcom/dataloader#568]
Hello,

I'm upgrading dataloader from v49 to v 56.0.4 and seeing below error.

Where could I specify database driver name.  In version v49  we do it in process.bat file 

ELSE (
    IF NOT EXIST "%AZL_JAVA_HOME%" (
        echo We couldn't find the Java Runtime Environment ^(JRE^) in directory "%AZL_JAVA_HOME%". To run process.bat, set the AZL_JAVA_HOME environment variable to the directory where the JRE is installed.
    ) ELSE (
        "%AZL_JAVA_HOME%\bin\java" -cp ..\dataloader-49.0.0-uber.jar;**ojdbc6.jar;terajdbc4.jar;redshift-jdbc42-2.1.0.1.jar;mssql-jdbc.jar** -Dsalesforce.config.dir=%1 com.salesforce.dataloader.process.ProcessRunner %PROCESS_OPTION%
    )
)

It seems you guys have added new folder util. i can't do that in process.bat anymore... getting error

<img width="895" alt="image" src="https://user-images.githubusercontent.com/18720022/197308287-39e727f3-01f7-4a07-b029-b77ee21c0e75.png">

**where should I mention driver name?**

Data Loader requires Java JRE 11 or later. Checking if it is installed...
[WSC][DataLoaderRunner.main:78]Log file already exists, appending to c:\dataloader\v56.0.4\INT\Files\status\accountMasterSoapTrace.log
[WSC][DataLoaderRunner.main:78]Log file already exists, appending to c:\dataloader\v56.0.4\INT\Files\status\accountMasterSoapTrace.log
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
20:25:04.934 [LNaccountUpsert] ERROR com.salesforce.dataloader.dao.database.DatabaseContext - Database error encountered during connecting for database configuration: LNAccountUpsert.  Sql error: Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'.
java.sql.SQLException: Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'
	at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:54) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:459) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:525) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.dao.database.DatabaseContext.initConnection(DatabaseContext.java:81) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.dao.database.DatabaseContext.checkConnection(DatabaseContext.java:73) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.dao.database.DatabaseReader.checkConnection(DatabaseReader.java:245) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.createDao(Controller.java:264) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.createMapper(Controller.java:273) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:168) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:290) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:78) ~[dataloader-56.0.4-uber.jar:?]
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:49) ~[dataloader-56.0.4-uber.jar:?]
	... 11 more
20:25:04.950 [LNaccountUpsert] FATAL com.salesforce.dataloader.controller.Controller - Error creating data access object
com.salesforce.dataloader.exception.DataAccessObjectInitializationException: Database error encountered during connecting for database configuration: LNAccountUpsert.  Sql error: Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'.
	at com.salesforce.dataloader.dao.database.DatabaseContext.initConnection(DatabaseContext.java:89) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.dao.database.DatabaseContext.checkConnection(DatabaseContext.java:73) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.dao.database.DatabaseReader.checkConnection(DatabaseReader.java:245) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.createDao(Controller.java:264) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.createMapper(Controller.java:273) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:168) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:290) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:78) ~[dataloader-56.0.4-uber.jar:?]
Caused by: java.sql.SQLException: Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'
	at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:54) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:459) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:525) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.dao.database.DatabaseContext.initConnection(DatabaseContext.java:81) ~[dataloader-56.0.4-uber.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.apache.commons.dbcp2.DriverFactory.createDriver(DriverFactory.java:49) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:459) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:525) ~[dataloader-56.0.4-uber.jar:?]
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.dao.database.DatabaseContext.initConnection(DatabaseContext.java:81) ~[dataloader-56.0.4-uber.jar:?]
	... 7 more
20:25:04.950 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process
com.salesforce.dataloader.exception.MappingInitializationException: Error creating data access object
	at com.salesforce.dataloader.controller.Controller.createMapper(Controller.java:275) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:168) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:290) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:78) ~[dataloader-56.0.4-uber.jar:?]
20:25:04.950 [main] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process
java.lang.RuntimeException: Error creating data access object
	at com.salesforce.dataloader.process.ProcessRunner.logErrorAndExitProcess(ProcessRunner.java:246) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:301) ~[dataloader-56.0.4-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:78) ~[dataloader-56.0.4-uber.jar:?]

**Comment by ashitsalesforce** [comment]
Hi @gvpatel , likely you are running into the issue that is fixed in PR #564 . You can copy/paste the content of the [latest process.bat](https://github.com/ashitsalesforce/dataloader/blob/master/release/win/bin/process.bat) here and check if your issue gets addressed.

**Comment by ashitsalesforce** [comment]
Hi @gvpatel , good to hear that database driver issue is resolved.

Regarding your log related issue, following seems to be the issue:
- You have set `LOG4J_CONFIGURATION_FILE` value to `C:\Dataloader\V56.0.4\INT\log-conf.xml`. 
- Data Loader code is trying to access `log-conf.xml` from `C:\Dataloader\v56.0.4\configs` folder (default if `LOG4J_CONFIGURATION_FILE` is not set) but is unable to due to insufficient access privileges.

Have you tried to re-launch the command line console (CMD.exe) after setting `LOG4J_CONFIGURATION_FILE`? If not, close the existing command line console and re-launch it to see if that makes data loader use `LOG4J_CONFIGURATION_FILE`.

**Comment by ashitsalesforce** [comment]
Hi @gvpatel , good to hear that the issue got resolved. Thanks for the update.
