### ISSUE TITLE
Cannot execute a batch process

### ISSUE THREAD

**Issue by raforeror** [forcedotcom/dataloader#577]
Hi,

I'm trying to execute a simple export task with a batch process but I'm getting the following error:

Data Loader requires Java JRE 11 or later. Checking if it is installed...
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
13:23:16.127 [extractAccounts] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process
java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.error(String, java.lang.Throwable)" because "com.salesforce.dataloader.controller.Controller.logger" is null
	at com.salesforce.dataloader.controller.Controller.<init>(Controller.java:126) ~[dataloader-56.0.6-uber.jar:?]
	at com.salesforce.dataloader.controller.Controller.getInstance(Controller.java:333) ~[dataloader-56.0.6-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:130) ~[dataloader-56.0.6-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:290) ~[dataloader-56.0.6-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:78) ~[dataloader-56.0.6-uber.jar:?]
13:23:16.169 [extractAccounts] FATAL com.salesforce.dataloader.process.ProcessRunner - Unable to run process
java.lang.RuntimeException: Cannot invoke "org.apache.logging.log4j.Logger.error(String, java.lang.Throwable)" because "com.salesforce.dataloader.controller.Controller.logger" is null
	at com.salesforce.dataloader.process.ProcessRunner.logErrorAndExitProcess(ProcessRunner.java:246) ~[dataloader-56.0.6-uber.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:301) ~[dataloader-56.0.6-uber.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:78) ~[dataloader-56.0.6-uber.jar:?]

**To Reproduce**
1.  Try to make an export from a .bat

This is happening on my windows laptop. Dataloader version 56.0.6 and Zulu 19

Thanks.

**Comment by ashitsalesforce** [comment]
Hi @raforeror , can you share your process-conf.xml, log-conf.xml, and config.properties? Make sure to remove any sensitive information such as username, password, and such before sharing.

**Comment by raforeror** [comment]
I reviewed and was all because a symbol in the .bat, sorry

**Comment by ashitsalesforce** [comment]
Thanks @raforeror for figuring out the root-cause and fixing it.
