### ISSUE TITLE
Should the new API version be 34.0.0 like the previous one was 33.0.0?

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/dataloader#73]
Just forked and tried rebuilding.  I'm getting an error on my mac.  It's not that I think the version number has anything to do with it.  It just may be coincidental.

```
[INFO] --- osxappbundle-maven-plugin:1.0-alpha-2:bundle (default) @ dataloader ---
[INFO] Setting property: classpath.resource.loader.class => 'org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader'.
[INFO] Setting property: file.resource.loader.class => 'org.apache.velocity.runtime.resource.loader.FileResourceLoader'.
[INFO] Setting property: file.resource.loader.path => ''.
[INFO] Setting property: resource.loader => 'file,classpath'.
[INFO] Building zip: /Users/tgagne/git/dataloader/target/dataloader-34.0-app.zip
[INFO] 
[INFO] --- exec-maven-plugin:1.1:exec (make-pretty-dmg) @ dataloader ---
[INFO] bash: /Users/tgagne/git/dataloader/yoursway-create-dmg/create-dmg: No such file or directory
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.531 s
[INFO] Finished at: 2015-04-22T15:13:15-04:00
[INFO] Final Memory: 35M/442M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:exec (make-pretty-dmg) on project dataloader: Result of /bin/sh -c cd /Users/tgagne/git/dataloader && bash make-pretty-dmg.sh /Users/tgagne/git/dataloader /Users/tgagne/git/dataloader/target/dataloader-34.0 /Users/tgagne/git/dataloader/target/dataloader-34.0-pretty.dmg execution is: '127'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:exec (make-pretty-dmg) on project dataloader: Result of /bin/sh -c cd /Users/tgagne/git/dataloader && bash make-pretty-dmg.sh /Users/tgagne/git/dataloader /Users/tgagne/git/dataloader/target/dataloader-34.0 /Users/tgagne/git/dataloader/target/dataloader-34.0-pretty.dmg execution is: '127'.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Result of /bin/sh -c cd /Users/tgagne/git/dataloader && bash make-pretty-dmg.sh /Users/tgagne/git/dataloader /Users/tgagne/git/dataloader/target/dataloader-34.0 /Users/tgagne/git/dataloader/target/dataloader-34.0-pretty.dmg execution is: '127'.
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:260)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
```

**Comment by diracz** [comment]
yoursway-create-dmg is a dependency that has not changed. 
Changing to 34.0 instead of 34.0.0 should not affect anything. It's because the wsc version has been changed the same way: https://github.com/forcedotcom/wsc/commits/master

Can you try pulling and building on the latest master branch?

**Comment by tggagne** [comment]
I did a pull from master and it built fine.  I wonder why my fork didn't 
build.  I'll try the fork again and see what happens.
