### ISSUE TITLE
Bean property 'configOverrideMap' is not writable or has an invalid setter method.

### ISSUE THREAD

**Issue by Jir22** [forcedotcom/dataloader#978]
Hi I'm facing issue with data loader 60.0.0, but tried also version 59.0.0 and it has been doing the same. We tried to migrate recently from old version 43.0.0 because of the Log4j vulnerability. 

Remark: sensitive info removed from path definitions, queries, logins etc.

**Error description**

[User] Error: UsersDTEv2_test.csv: ERROR [main] process.ProcessConfig getProcessInstance (ProcessConfig.java:98) - Error loading process: C configuration from config file: \\...\DataLoader\bin\conf\rg3l3dfz.4dw\process-conf.xml
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'C' defined in URL [file:.../DataLoader/bin/conf/rg3l3dfz.4dw/process-conf.xml]: Invalid property 'configOverrideMap' of bean class [com.salesforce.dataloader.process.DataLoaderRunner]: Bean property 'configOverrideMap' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1718) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:344) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[dataloader-59.0.0.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1155) ~[dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:95) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:308) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:254) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:101) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:83) [dataloader-59.0.0.jar:?]
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'configOverrideMap' of bean class [com.salesforce.dataloader.process.DataLoaderRunner]: Bean property 'configOverrideMap' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:214) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:431) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:279) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:267) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:104) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:79) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1715) ~[dataloader-59.0.0.jar:?]
	... 11 more
2024-02-10 04:02:15,597 FATAL [main] process.ProcessRunner logErrorAndExitProcess (ProcessRunner.java:244) - Unable to run process
com.salesforce.dataloader.exception.ProcessInitializationException: Error loading process: C configuration from config file: ...\DataLoader\bin\conf\rg3l3dfz.4dw\process-conf.xml
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:99) ~[dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.getInstance(ProcessRunner.java:308) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:254) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:101) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:83) [dataloader-59.0.0.jar:?]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'C' defined in URL [file:.../DataLoader/bin/conf/rg3l3dfz.4dw/process-conf.xml]: Invalid property 'configOverrideMap' of bean class [com.salesforce.dataloader.process.DataLoaderRunner]: Bean property 'configOverrideMap' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1718) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:344) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[dataloader-59.0.0.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1155) ~[dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:95) ~[dataloader-59.0.0.jar:?]
	... 4 more
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'configOverrideMap' of bean class [com.salesforce.dataloader.process.DataLoaderRunner]: Bean property 'configOverrideMap' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:214) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:431) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:279) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:267) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:104) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:79) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1715) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:597) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:344) ~[dataloader-59.0.0.jar:?]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[dataloader-59.0.0.jar:?]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1155) ~[dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.ProcessConfig.getProcessInstance(ProcessConfig.java:95) ~[dataloader-59.0.0.jar:?]
	... 4 more
2024-02-10 04:02:15,599 FATAL [main] process.ProcessRunner logErrorAndExitProcess (ProcessRunner.java:244) - Unable to run process
java.lang.RuntimeException: Error loading process: C configuration from config file: \\...\DataLoader\bin\conf\rg3l3dfz.4dw\process-conf.xml
	at com.salesforce.dataloader.process.ProcessRunner.logErrorAndExitProcess(ProcessRunner.java:245) ~[dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.ProcessRunner.runBatchMode(ProcessRunner.java:270) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.runApp(DataLoaderRunner.java:101) [dataloader-59.0.0.jar:?]
	at com.salesforce.dataloader.process.DataLoaderRunner.main(DataLoaderRunner.java:83) [dataloader-59.0.0.jar:?]

**process-conf.xml**
![image](https://github.com/forcedotcom/dataloader/assets/159769965/d1ab6221-b2d5-40e1-a1a6-1649eb847bed)

**log-conf.xml**
![image](https://github.com/forcedotcom/dataloader/assets/159769965/d18d9406-14c3-495c-8687-23af71807382)

**Comment by Jir22** [comment]
**process-conf.xml**

<?xml version="1.0"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd"[]>
<beans>
  <bean id="C" class="com.salesforce.dataloader.process.DataLoaderRunner" scope="prototype">
    <description>get info from salesforce and save into a CSV file."</description>
    <property name="name" value="C" />
    <property name="configOverrideMap">
      <map>
        <entry key="sfdc.debugMessages" value="true" />
        <entry key="sfdc.debugMessagesFile" value="\\...\DataLoader\bin\status\sfdcSoapTrace.log" />
	<entry key="process.outputError" value="\\...\DataLoader\bin\status\sfdcErrorLog.log" />
        <entry key="sfdc.endpoint" value="https://...my.salesforce.com" />
        <entry key="sfdc.username" value="xxxREMOVEDxxx" />
        <entry key="sfdc.password" value="xxxREMOVEDxxx" />
        <entry key="process.encryptionKeyFile" value="\\....\DataLoader\bin\sample.key" />
        <entry key="sfdc.timeoutSecs" value="6000" />
        <entry key="sfdc.enableRetries" value="true" />
        <entry key="sfdc.maxRetries" value="10" />
        <entry key="sfdc.minRetrySleepSecs" value="10" />
        <entry key="sfdc.connectionTimeoutSecs" value="600" />
        <entry key="sfdc.loadBatchSize" value="100" />
        <entry key="sfdc.entity" value="User" />
        <entry key="sfdc.extractionRequestSize" value="2000" />
        <entry key="sfdc.extractionSOQL" value="SELECT IsActive,Id,Username,Name,Alias,Email,country,profile.name,lastlogindate,createddate,systemmodstamp ... FROM User where country = .... and SystemModstamp = ,..." />
        <entry key="process.operation" value="extract" />
        <entry key="dataAccess.type" value="csvWrite" />
	<entry key="dataAccess.writeUTF8" value="true" />
	<entry key="dataAccess.readBatchSize" value="200" />
        <entry key="dataAccess.name" value="\\...\Salesforce\UsersDTEv2_test.csv" />
	<entry key="sfdc.useBulkApi" value="false" />
	<entry key="sfdc.bulkApiSerialMode" value="false" />
	<entry key="sfdc.bulkApiCheckStatusInterval" value="5000" />
      </map>
    </property>
  </bean>
</beans>



**log-conf.xml**

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appenders>
    <File name="fileAppender" fileName="${sys:java.io.tmpdir}/sdl.log" append="true">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </File>
    <CONSOLE name="STDOUT" target="SYSTEM_OUT">
      <PatternLayout pattern="%d %-5p [%t] %C{2} %M (%F:%L) - %m%n"/>
    </CONSOLE>
  </appenders>
  <loggers>
    <logger name="org.apache.log4j.xml" level="warn">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </logger>
    <logger name="org.apache" level="warn">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </logger>
    <root level="info">
      <AppenderRef ref="fileAppender"/>
      <AppenderRef ref="STDOUT" />
    </root>
  </loggers>
</configuration>

**Comment by ashitsalesforce** [comment]
hi @Jir22 ,

Change bean's class attribute from `class="com.salesforce.dataloader.process.DataLoaderRunner"` to `class="com.salesforce.dataloader.process.ProcessRunner"` and try.

**Comment by Jir22** [comment]
Hi, it unf. didn't help. I changed the value in process-congf.xml   (back) to com.salesforce.dataloader.process.ProcessRunner as was suggested. Now it does not report any error but also does not create any file. 
I tried to run it in CMD with help of process.bat file, as suggested here
https://developer.salesforce.com/docs/atlas.en-us.dataLoader.meta/dataLoader/using_the_command_line_interface.htm
so that I can better output details together with switching of logging level in log-conf.xml to "trace". But I couldn't find any new sdl.log file under my temp folder, nor the files defined in proces-conf were updated with new entries.

Anyway the final output is an error message:
  

CMD command:
C:\Users\jir22>\\...\DataLoader\bin\process.bat "\\...\DataLoader\bin\conf"

Which does:
C:\Users\jir22>"\\...\DataLoader\jdk-17.0.9\bin\java" -cp \\...\DataLoader\dataloader-59.0.0.jar com.salesforce.dataloader.process.ProcessRunner salesforce.config.dir=\\...\DataLoader\bin\conf run.mode=batch process.name=C


Error: Main method not found in class com.salesforce.dataloader.process.ProcessRunner, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

**Comment by ashitsalesforce** [comment]
Hi @Jir22 ,

You are likely executing a version of `process.bat` that's not shipped in v59.0. Can you verify the following?
1. You are executing `process.bat` script located in `<data loader v59.0.0 installation root>\process` folder.
2. content of `process.bat` script you are executing is
```
@echo off
CALL "%~dp0..\util\util.bat" :runDataLoader %* run.mode=batch
```
3. lines 53 to 56 of `util.bat` script, located in `<data loader v59.0.0 installation root>\util` folder are:
```
:runDataLoader
    CALL :checkJavaVersion
    java -cp "%~dp0..\*" com.salesforce.dataloader.process.DataLoaderRunner %*
    EXIT /b %ERRORLEVEL%
```

**Comment by ashitsalesforce** [comment]
Closing assuming that the issue is resolved using the provided information.

**Comment by ashitsalesforce** [comment]
Closing assuming that issue is resolved.

**Comment by Jir22** [comment]
Hi, we managed to get it working with a fresh installation of dataloader. There were some missing pieces when we tried to merge old folder structure with new one. Thanks for the support!
